# Generated by Django 5.2.8 on 2025-11-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0012_delete_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='avatar_personagem',
            field=models.ImageField(default="{% static 'img/default-avatar.jpg' %}", upload_to='personagens/', verbose_name='avatar'),
        ),
    ]
