# Generated by Django 5.2.8 on 2025-11-27 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0016_alter_personagem_avatar_personagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_genero', models.CharField(max_length=50, verbose_name='gênero')),
            ],
            options={
                'verbose_name': 'Gênero de Campanha',
                'verbose_name_plural': 'Gêneros de Campanha',
                'ordering': ('nome_genero',),
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_raca', models.CharField(blank=True, max_length=100, null=True, verbose_name='raça')),
            ],
            options={
                'verbose_name': 'Raças',
                'verbose_name_plural': 'Raças',
                'ordering': ('nome_raca',),
            },
        ),
        migrations.AlterField(
            model_name='personagem',
            name='avatar_personagem',
            field=models.ImageField(upload_to='personagens/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='campanhas', to='area_administrativa.generocampanha', verbose_name='gêneros'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personagens', to='area_administrativa.raca'),
        ),
    ]
